/**
 * Engram — Update Manifest State Machine
 * =======================================
 *
 * Manages .engram-update.jsonc — the per-category diff that powers /engram-update.
 * Generated by writeUpdateManifest() on version bump; consumed by the pseudo-command
 * template for interactive auto/manual/per-file update flows.
 *
 * State machine: pending → in_progress → (file deleted on completion)
 * Categories: skills, agents, scripts, command — each with { added, skipped } arrays.
 *
 * Manual mode saves per-file checkpoints by removing processed files from skipped[]
 * via node -e (see pseudo-command template in index.ts).
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync, unlinkSync, readdirSync, copyFileSync } from "node:fs"
import { resolve, relative } from "node:path"
import { parseFrontmatter } from "./parse-frontmatter.js"

const SKILLS_DIR = "skills"
const AGENTS_DIR = "agents"
const SCRIPTS_DIR = "scripts"
const COMMANDS_DIR = "command"

/** Tracks files per category: added (new on disk), skipped (preserved, needs user decision). */
export interface DiffEntry {
  added: string[]
  skipped: string[]
}

/** Full update manifest. remaining tracks unprocessed categories; applied tracks completed. */
export interface Manifest {
  from: string
  to: string
  source: string
  categories: Record<string, DiffEntry>
  state: "pending" | "in_progress"
  applied: string[]
  remaining: string[]
}

/** Recursively walks a directory, returning relative paths from base. Returns [] if dir absent. */
function walkFiles(dir: string, base: string): string[] {
  const files: string[] = []
  if (!existsSync(dir)) return files
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = resolve(dir, entry.name)
    const rel = relative(base, full)
    if (entry.isDirectory()) {
      files.push(...walkFiles(full, base))
    } else {
      files.push(rel)
    }
  }
  return files
}

/** Compares source (packageRoot/category) vs destination (target/category) files. */
function diffCategory(packageRoot: string, target: string, category: string): DiffEntry {
  const srcDir = resolve(packageRoot, category)
  const destDir = resolve(target, category)
  const srcFiles = walkFiles(srcDir, packageRoot)
  const destFiles = new Set(walkFiles(destDir, target))
  const added: string[] = []
  const skipped: string[] = []
  for (const f of srcFiles) {
    const destRel = resolve(target, f)
    if (!existsSync(destRel)) {
      added.push(f)
    } else {
      skipped.push(f)
    }
  }
  return { added, skipped }
}

/** Rewrites an agent markdown file in-place to OpenCode YAML format (mode: subagent, hidden: true). */
function transformAgentAt(filePath: string) {
  const content = readFileSync(filePath, "utf-8")
  const { attrs, body } = parseFrontmatter(content)
  const newAttrs: Record<string, any> = {}
  if (attrs.name) newAttrs.name = attrs.name
  if (attrs.description) newAttrs.description = attrs.description
  newAttrs.mode = "subagent"
  newAttrs.hidden = true
  if (attrs.tools && typeof attrs.tools === "string") {
    const toolObj: Record<string, boolean> = {}
    for (const tool of attrs.tools.split(",")) {
      const trimmed = tool.trim()
      if (trimmed) toolObj[trimmed] = true
    }
    if (Object.keys(toolObj).length > 0) newAttrs.tools = toolObj
  }
  const yamlLines: string[] = []
  for (const [k, v] of Object.entries(newAttrs)) {
    if (v == null) continue
    if (typeof v === "object") {
      yamlLines.push(`${k}:`)
      for (const [kk, vv] of Object.entries(v)) yamlLines.push(`  ${kk}: ${vv}`)
    } else {
      yamlLines.push(`${k}: ${v}`)
    }
  }
  writeFileSync(filePath, `---\n${yamlLines.join("\n")}\n---\n\n${body.trimEnd()}\n`)
}

/** Generates .engram-update.jsonc on version bump. Diffs all 4 categories, writes manifest with state="pending". */
export function writeUpdateManifest(packageRoot: string, target: string, prevVersion: string, version: string) {
  const categories: Record<string, DiffEntry> = {}
  const remaining: string[] = []
  for (const cat of [SKILLS_DIR, AGENTS_DIR, SCRIPTS_DIR, COMMANDS_DIR]) {
    categories[cat] = diffCategory(packageRoot, target, cat)
    if (categories[cat].skipped.length) remaining.push(cat)
  }
  const manifest: Manifest = {
    from: prevVersion,
    to: version,
    source: packageRoot,
    categories,
    state: "pending",
    applied: [],
    remaining,
  }
  writeFileSync(resolve(target, ".engram-update.jsonc"), JSON.stringify(manifest, null, 2))
}

/** Persists manifest to disk. Used by per-file checkpointing (node -e in the template). */
export function saveManifest(target: string, manifest: Manifest) {
  writeFileSync(resolve(target, ".engram-update.jsonc"), JSON.stringify(manifest, null, 2))
}

/** True when .engram-update.jsonc exists (used to register /engram-update pseudo-command). */
export function hasPendingUpdate(target: string): boolean {
  return existsSync(resolve(target, ".engram-update.jsonc"))
}

/** Reads and parses .engram-update.jsonc. Returns null if absent or corrupt JSON. */
export function readManifest(target: string): Manifest | null {
  const f = resolve(target, ".engram-update.jsonc")
  if (!existsSync(f)) return null
  try {
    return JSON.parse(readFileSync(f, "utf-8")) as Manifest
  } catch {
    return null
  }
}

/** Human-readable summary for notifications: "Engram X → Y. N skills added, M agents preserved…". Returns null if no manifest. */
export function getUpdateSummary(target: string): string | null {
  const m = readManifest(target)
  if (!m) return null
  const lines: string[] = [`Engram ${m.from} → ${m.to}.`]
  for (const [cat, diff] of Object.entries(m.categories)) {
    const parts: string[] = []
    if (diff.added.length) parts.push(`${diff.added.length} ${cat} added`)
    if (diff.skipped.length) parts.push(`${diff.skipped.length} ${cat} preserved`)
    if (parts.length) lines.push(`  ${parts.join(", ")}.`)
  }
  lines.push("Run /engram-update to pick what to refresh: auto (all) or manual (per category).")
  return lines.join("\n")
}

export function applyUpdate(target: string, category: string, sources: string[]) {
  const m = readManifest(target)
  if (!m) return 0
  let count = 0
  for (const relPath of sources) {
    if (!relPath.startsWith(category + "/")) continue
    const src = resolve(m.source, relPath)
    const dest = resolve(target, relPath)
    if (!existsSync(src)) continue
    mkdirSync(resolve(dest, ".."), { recursive: true })
    copyFileSync(src, dest)
    if (category === AGENTS_DIR) transformAgentAt(dest)
    count++
  }
  return count
}

/** Deletes .engram-update.jsonc. Called when update is resolved (auto/keep-as-is/cleanup). */
export function clearUpdate(target: string) {
  const f = resolve(target, ".engram-update.jsonc")
  if (existsSync(f)) unlinkSync(f)
}
